### ISSUE TITLE
Can we remove the need for --privileged altogether?

### ISSUE THREAD

**Issue by rankun203** [wazum/openconnect-proxy#8]
Currently it's asking for --privileged, otherwise the server won't be fully connected to the VPN, requesting socks will still use client machine network.

openconnect supports `--script-tun` to tunnel its VPN traffic into another program, say https://github.com/cernekee/ocproxy

**Comment by barpaw** [comment]
@rankun203 👋
I've implemented exactly the solution you're referring to, and it's available in my repository: [openconnect-ocproxy](https://github.com/barpaw/openconnect-ocproxy).

**Comment by rankun203** [comment]
@barpaw haha nice! I also implemented that back then https://github.com/rankun203/openconnect-proxy.
